[project]
name = "call_me_maybe"
version = "0.1.0"
requires-python = ">=3.11"
readme = "README.md"
authors = [
    { name = "maprunty", email = "maprunty@student.42heilbronn.de" }
]
dependencies = [
	"numpy",
    	"pydantic",
	"llm_sdk",
]


[tool.uv.sources]
llm_sdk = { path = "llm_sdk/dist/llm_sdk-0.1.0-py3-none-any.whl" }



[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "flake8-docstrings>=1.7.0",
    "mypy>=2.0.0",
    "ipython>=9.17.1",
]

[tool.mypy]
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
exclude = '(^libs/mlx/)|(^\.venv/)|(/build/)|(^dist/)'

[tool.flake8]
exclude  = ".git, __pycache__, build, dist, libs/mlx, .venv"
extend-ignore = "E203, D401"
